baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Chengjin 的技术博客'
theme = 'mtp-theme'

[params]
  author = "Chengjin"
  description = "Free AI-Powered Tools and Useful Online Utilities"

